2017-12-13 10:04:06.5753-----------0001:PushServer Start Logging---------------------
2017-12-13 10:04:06.3091| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/   
2017-12-13 10:04:06.9004|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/ 
Connection:keep-alive
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
 
2017-12-13 10:04:06.9819|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(404) GET http://localhost:5000/  (Duration = 00:00:00.2343608)
 
2017-12-13 10:04:06.9819| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=693.2204, StatusCode=404, ContentType=, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 693.2204ms 404  
2017-12-13 10:04:14.9923| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 10:04:15.0368| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), Arguments=, ValidationState=Valid, EventId_Id=1, EventId_Name=, EventId=1
Executing action method PushServer.Controllers.PushMessageController.Get (PushServer) with arguments ((null)) - ModelState is Valid 
2017-12-13 10:04:15.1471| INFO ||Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor|  |Value=Microsoft.AspNetCore.Mvc.ControllerContext, EventId_Id=1, EventId_Name=, EventId=1
Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext. 
2017-12-13 10:04:15.2181| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=190.2684, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 190.2684ms 
2017-12-13 10:04:15.2181| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=236.8031, StatusCode=200, ContentType=application/json; charset=utf-8, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 236.8031ms 200 application/json; charset=utf-8 
2017-12-13 10:04:36.4551| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 10:04:36.4688| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), Arguments=, ValidationState=Valid, EventId_Id=1, EventId_Name=, EventId=1
Executing action method PushServer.Controllers.PushMessageController.Get (PushServer) with arguments ((null)) - ModelState is Valid 
2017-12-13 10:04:36.4907| INFO ||Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor|  |Value=Microsoft.AspNetCore.Mvc.ControllerContext, EventId_Id=1, EventId_Name=, EventId=1
Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext. 
2017-12-13 10:04:36.5065| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=44.8768, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 44.8768ms 
2017-12-13 10:04:36.5174| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=62.3333, StatusCode=200, ContentType=application/json; charset=utf-8, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 62.3333ms 200 application/json; charset=utf-8 
2017-12-13 10:06:46.3808| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 10:06:46.6242| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), Arguments=, ValidationState=Valid, EventId_Id=1, EventId_Name=, EventId=1
Executing action method PushServer.Controllers.PushMessageController.Get (PushServer) with arguments ((null)) - ModelState is Valid 
2017-12-13 10:06:46.7080| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=92.5648, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 92.5648ms 
2017-12-13 10:06:46.7740|ERROR ||Microsoft.AspNetCore.Server.Kestrel|  |ConnectionId=0HLA1POKSMN6M, TraceIdentifier=0HLA1POKSMN6M:00000001, EventId_Id=13, EventId_Name=, EventId=13
Connection id "0HLA1POKSMN6M", Request id "0HLA1POKSMN6M:00000001": An unhandled exception was thrown by the application.System.Exception: Self , ERROR
   at PushServer.Controllers.PushMessageController.Get() in D:\Workspace\Foya\FoyaService\DotNetCore\PushServer\Controllers\PushMessageController.cs:line 30
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext() 
2017-12-13 10:06:46.8517| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=476.5551, StatusCode=500, ContentType=, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 476.5551ms 500  
2017-12-13 10:07:36.9994-----------0001:PushServer End   Logging---------------------
2017-12-13 10:11:29.8767| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 10:11:30.0609| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), Arguments=, ValidationState=Valid, EventId_Id=1, EventId_Name=, EventId=1
Executing action method PushServer.Controllers.PushMessageController.Get (PushServer) with arguments ((null)) - ModelState is Valid 
2017-12-13 10:11:30.0942| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=41.3364, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 41.3364ms 
2017-12-13 10:11:30.1244|ERROR ||Microsoft.AspNetCore.Server.Kestrel|  |ConnectionId=0HLA1PR9CHE07, TraceIdentifier=0HLA1PR9CHE07:00000001, EventId_Id=13, EventId_Name=, EventId=13
Connection id "0HLA1PR9CHE07", Request id "0HLA1PR9CHE07:00000001": An unhandled exception was thrown by the application.System.Exception: Self , ERROR
   at PushServer.Controllers.PushMessageController.Get() in D:\Workspace\Foya\FoyaService\DotNetCore\PushServer\Controllers\PushMessageController.cs:line 30
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext() 
2017-12-13 10:11:30.1945| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=322.0568, StatusCode=500, ContentType=, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 322.0568ms 500  
2017-12-13 10:12:12.5926-----------0001:PushServer End   Logging---------------------
2017-12-13 10:12:43.2353| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 10:12:43.4509| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), Arguments=, ValidationState=Valid, EventId_Id=1, EventId_Name=, EventId=1
Executing action method PushServer.Controllers.PushMessageController.Get (PushServer) with arguments ((null)) - ModelState is Valid 
2017-12-13 10:12:43.4884| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=45.3066, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 45.3066ms 
2017-12-13 10:12:43.6111| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=380.9262, StatusCode=500, ContentType=application/json, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 380.9262ms 500 application/json 
2017-12-13 10:13:18.6592-----------0001:PushServer End   Logging---------------------
2017-12-13 10:40:55.7710| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/   
2017-12-13 10:40:56.1650|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/ 
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Language:zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
Host:localhost:5000
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Upgrade-Insecure-Requests:1
 
2017-12-13 10:40:56.5086|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(404) GET http://localhost:5000/  (Duration = 00:00:00.4033448)
 
2017-12-13 10:40:56.5214| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=758.6706, StatusCode=404, ContentType=, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 758.6706ms 404  
2017-12-13 10:41:05.5855| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 10:41:05.5918|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/api/PushMessage 
Cache-Control:no-cache
Connection:keep-alive
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
Authorization:123YAYA
Host:localhost:5000
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Postman-Token:cbeecd62-7780-e821-6494-450ec6d688b1
 
2017-12-13 10:41:05.6357| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), Arguments=, ValidationState=Valid, EventId_Id=1, EventId_Name=, EventId=1
Executing action method PushServer.Controllers.PushMessageController.Get (PushServer) with arguments ((null)) - ModelState is Valid 
2017-12-13 10:41:05.6714| INFO ||Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor|  |Value=Microsoft.AspNetCore.Mvc.ControllerContext, EventId_Id=1, EventId_Name=, EventId=1
Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext. 
2017-12-13 10:41:05.7408| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=114.0231, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 114.0231ms 
2017-12-13 10:41:05.7534|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(200) GET http://localhost:5000/api/PushMessage  (Duration = 00:00:00.1618711)
Content-Type:application/json; charset=utf-8
["value3","value4"] 
2017-12-13 10:41:05.7654| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=179.9053, StatusCode=200, ContentType=application/json; charset=utf-8, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 179.9053ms 200 application/json; charset=utf-8 
2017-12-13 10:41:25.8266| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 10:41:25.8547|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/api/PushMessage 
Cache-Control:no-cache
Connection:keep-alive
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
Authorization:123YAYA
Host:localhost:5000
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
 
2017-12-13 10:41:25.8818| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), Arguments=, ValidationState=Valid, EventId_Id=1, EventId_Name=, EventId=1
Executing action method PushServer.Controllers.PushMessageController.Get (PushServer) with arguments ((null)) - ModelState is Valid 
2017-12-13 10:41:25.9061| INFO ||Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor|  |Value=Microsoft.AspNetCore.Mvc.ControllerContext, EventId_Id=1, EventId_Name=, EventId=1
Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext. 
2017-12-13 10:41:25.9247| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=43.2564, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 43.2564ms 
2017-12-13 10:41:25.9538|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(200) GET http://localhost:5000/api/PushMessage  (Duration = 00:00:00.1162115)
Content-Type:application/json; charset=utf-8
["value3","value4"] 
2017-12-13 10:41:25.9685| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=141.8906, StatusCode=200, ContentType=application/json; charset=utf-8, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 141.8906ms 200 application/json; charset=utf-8 
2017-12-13 10:43:08.2912| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/   
2017-12-13 10:43:08.5645|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/ 
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Language:zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
Upgrade-Insecure-Requests:1
 
2017-12-13 10:43:08.7402|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(404) GET http://localhost:5000/  (Duration = 00:00:00.2703057)
 
2017-12-13 10:43:08.7924| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=506.8644, StatusCode=404, ContentType=, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 506.8644ms 404  
2017-12-13 10:43:13.1832| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 10:43:13.1893|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/api/PushMessage 
Cache-Control:no-cache
Connection:keep-alive
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
Authorization:123
Host:localhost:5000
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Postman-Token:8697da1d-dbae-53e6-6b15-5a14b25b8aee
 
2017-12-13 10:43:28.4878| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=15260.7542, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 15260.7542ms 
2017-12-13 10:43:28.6275|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(500) GET http://localhost:5000/api/PushMessage  (Duration = 00:00:15.4383964)
Content-Type:application/json
{"error":"Auth failed"} 
2017-12-13 10:43:28.6447| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=15461.5208, StatusCode=500, ContentType=application/json, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 15461.5208ms 500 application/json 
2017-12-13 11:03:28.8744| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/   
2017-12-13 11:03:29.1509|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/ 
Connection:keep-alive
Accept-Encoding:gzip, deflate, br
Upgrade-Insecure-Requests:1
 
2017-12-13 11:03:29.2875|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(404) GET http://localhost:5000/  (Duration = 00:00:00.2083231)
 
2017-12-13 11:03:29.3023| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=440.1373, StatusCode=404, ContentType=, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 440.1373ms 404  
2017-12-13 11:03:35.3886| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 11:03:35.3886|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/api/PushMessage 
Cache-Control:no-cache
Connection:keep-alive
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
Host:localhost:5000
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Postman-Token:61379065-561f-0096-4c2a-b240aa61a199
 
2017-12-13 11:03:42.6844| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=7250.7013, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 7250.7013ms 
2017-12-13 11:03:42.8193|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(500) GET http://localhost:5000/api/PushMessage  (Duration = 00:00:07.4243844)
Content-Type:application/json
{"error":"Object reference not set to an instance of an object."} 
2017-12-13 11:03:42.8295| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=7440.8955, StatusCode=500, ContentType=application/json, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 7440.8955ms 500 application/json 
2017-12-13 11:04:22.6353| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/   
2017-12-13 11:04:22.8481|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/ 
Connection:keep-alive
Upgrade-Insecure-Requests:1
 
2017-12-13 11:04:22.9870|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(404) GET http://localhost:5000/  (Duration = 00:00:00.2049177)
 
2017-12-13 11:04:22.9999| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=371.3573, StatusCode=404, ContentType=, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 371.3573ms 404  
2017-12-13 11:04:26.2726| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 11:04:26.2822|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/api/PushMessage 
Cache-Control:no-cache
Connection:keep-alive
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
Host:localhost:5000
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Postman-Token:b84f2547-fe3d-de60-1faa-d74681d4fb6e
 
2017-12-13 11:04:30.9514| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=4628.5333, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 4628.5333ms 
2017-12-13 11:04:31.0706|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(500) GET http://localhost:5000/api/PushMessage  (Duration = 00:00:04.7921751)
Content-Type:application/json
{"error":"Authorization is error."} 
2017-12-13 11:04:31.0806| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=4807.3515, StatusCode=500, ContentType=application/json, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 4807.3515ms 500 application/json 
2017-12-13 11:10:32.8931| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/   
2017-12-13 11:10:33.1156|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/ 
Connection:keep-alive
Accept-Encoding:gzip, deflate, br
Host:localhost:5000
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Upgrade-Insecure-Requests:1
 
2017-12-13 11:10:33.2322|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(404) GET http://localhost:5000/  (Duration = 00:00:00.1801026)
 
2017-12-13 11:10:33.2322| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=361.9182, StatusCode=404, ContentType=, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 361.9182ms 404  
2017-12-13 11:10:36.4933| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |Protocol=HTTP/1.1, Method=GET, ContentType=, ContentLength=, Scheme=http, Host=localhost:5000, PathBase=, Path=/api/PushMessage, QueryString=, EventId_Id=1, EventId_Name=, EventId=1
Request starting HTTP/1.1 GET http://localhost:5000/api/PushMessage   
2017-12-13 11:10:36.5053|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Request GET http://localhost:5000/api/PushMessage 
Cache-Control:no-cache
Connection:keep-alive
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
Host:localhost:5000
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Postman-Token:bb777cbb-5899-f5c6-5382-969799a11646
 
2017-12-13 11:10:40.8746| INFO ||Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|  |ActionName=PushServer.Controllers.PushMessageController.Get (PushServer), ElapsedMilliseconds=4321.5133, EventId_Id=2, EventId_Name=, EventId=2
Executed action PushServer.Controllers.PushMessageController.Get (PushServer) in 4321.5133ms 
2017-12-13 11:10:41.0702|DEBUG ||WDev.AspNetCore.Middleware.HttpLoggingMiddleware|  |
Response(403) GET http://localhost:5000/api/PushMessage  (Duration = 00:00:04.5658337)
Content-Type:application/json
{"Code":403,"Msg":"Authorization is error."} 
2017-12-13 11:10:41.0905| INFO ||Microsoft.AspNetCore.Hosting.Internal.WebHost|  |ElapsedMilliseconds=4597.144, StatusCode=403, ContentType=application/json, EventId_Id=2, EventId_Name=, EventId=2
Request finished in 4597.144ms 403 application/json 
